language: android
android:
  components:
    - tools 
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-25
  
  licenses:
    - android-sdk-license-.+
    - '.+' 

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - ./gradlew build connectedCheck
  - ./gradlew findbugs -Pandroid.useDexArchive=false
  - ./gradlew lint -Pandroid.useDexArchive=false
  - ./gradlew checkstyle -Pandroid.useDexArchive=false

after_failure: 
  - "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
